# -*- coding: utf-8 -*-
"""체크카드_신규발급_forDag.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eJ9wHODI4s2NRF11PX9Rrw1fmFPJeXKw

# [Cell 1] 구글 드라이브 마운트
"""

# from google.colab import drive
# drive.mount('/content/drive')

"""# [Cell 2] 라이브러리 설치"""

# !apt-get update -qq
# !wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | apt-key add -
# !bash -lc 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" > /etc/apt/sources.list.d/google-chrome.list'
# !apt-get update -qq
# !apt-get install -y google-chrome-stable
# !pip install -U selenium webdriver-manager beautifulsoup4 tqdm lxml
# !pip install -U requests pandas

# # 버전 확인
# !google-chrome --version
# !chromedriver --version || echo "chromedriver는 webdriver-manager가 자동 설치합니다."
# !python -m pip show selenium

"""# [Cell 4] API 헬퍼 함수,  Selenium 드라이버 설정 함수

### 1. API 헬퍼 함수 (필터링용)
"""

import time
import re
import json
import os
import random
from typing import Dict, Any, List, Optional, Set

# API 요청용
import requests
from requests.adapters import HTTPAdapter
from urllib3.util.retry import Retry

# Selenium 스크래핑용
from bs4 import BeautifulSoup
from tqdm import tqdm
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.common.exceptions import TimeoutException
from webdriver_manager.chrome import ChromeDriverManager

RETRY_TOTAL  = 5
TIMEOUT_SECS = 10

# ===================== API 세션 빌드 =====================
def build_session() -> requests.Session:
    """재시도 로직이 포함된 requests.Session을 생성합니다."""
    s = requests.Session()
    retries = Retry(
        total=RETRY_TOTAL,
        backoff_factor=RETRY_BACKOFF_FACTOR,
        status_forcelist=[429, 500, 502, 503, 504],
        allowed_methods=["GET"],
        raise_on_status=False,
    )
    adapter = HTTPAdapter(max_retries=retries)
    s.mount("http://", adapter)
    s.mount("https://", adapter)
    s.headers.update({
        "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36"
    })
    return s

# ===================== API 카드 정보 호출 (디버깅 추가) =====================
def fetch_card(session: requests.Session, cid: int) -> Optional[Dict[str, Any]]:
    """API를 호출하여 카드의 JSON 데이터를 가져옵니다."""
    url = API_BASE_URL.format(id=cid)
    try:
        r = session.get(url, timeout=TIMEOUT_SECS)
    except requests.RequestException as e:
        return {"_error": str(e), "id": cid}

    if r.status_code == 404:
        return None  # 없는 카드

    # 상태 코드가 200번대가 아니면 에러 처리
    if not (200 <= r.status_code < 300):
        return {"_http_status": r.status_code, "id": cid}

    try:
        data = r.json()
    except ValueError:
        # 🔴 [디버깅] JSON 파싱 실패 시, 도대체 뭘 받았는지 앞부분 200글자만 찍어봅니다.
        # print(f"\n[DEBUG] ID {cid} 응답 내용 확인: {r.text[:200]}")
        return {"_parse_error": True, "id": cid}

    if not any(k in data for k in ("id","card_id","cardId")):
        data["id"] = cid
    return data

# ===================== 신규발급 중단 필터 =====================
def is_discontinued(obj: Dict[str, Any]) -> bool:
    """
    응답 JSON에서 신규발급/판매 중단을 의미하는 신호가 있으면 True를 반환합니다.
    (카드고릴라_크롤링.ipynb 로직 사용)
    """
    KEY_CANDIDATES = [
        "isIssuable", "issuable", "issueStop", "isIssueStopped",
        "applyAvailable", "applyStatus", "salesStatus",
        "serviceStatus", "status", "openStatus"
    ]
    BAD_STRINGS = {"n", "false", "0", "end", "stop", "closed", "close"}
    KOREAN_FLAGS = ["신규발급이 중단", "발급이 중단", "판매중지", "판매 중단", "단종", "종료"]

    # 1) 전형적인 상태 키 점검
    for k in KEY_CANDIDATES:
        if k in obj:
            v = obj[k]
            if isinstance(v, str):
                vs = v.strip().lower()
                if (vs in BAD_STRINGS) or any(flag in v for flag in KOREAN_FLAGS):
                    return True
            elif isinstance(v, (int, bool)):
                if v in (0, False):
                    return True

    # 2) 모든 문자열 필드에서 문구 스캔 (재귀)
    def walk(x):
        if isinstance(x, dict):
            for vv in x.values():
                if walk(vv): return True
        elif isinstance(x, list):
            for vv in x:
                if walk(vv): return True
        elif isinstance(x, str):
            s = x.strip()
            if any(flag in s for flag in KOREAN_FLAGS):
                return True
        return False

    return walk(obj)

"""### 2. Selenium 헬퍼 함수 (스크래핑용)"""

# ===================== 드라이버 설정 (v4) =====================
def setup_driver():
    """Selenium Chrome 드라이버를 설정합니다."""
    chrome_options = Options()
    # chrome_options.add_argument("--headless=new")
    chrome_options.add_argument("--start-maximized") 

    chrome_options.add_argument("--disable-gpu")
    chrome_options.add_argument("--disable-software-rasterizer")
    
    chrome_options.add_argument("--no-sandbox")
    chrome_options.add_argument("--disable-dev-shm-usage")
    chrome_options.add_argument("--window-size=1280,2200")
    chrome_options.add_argument("user-agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.102 Safari/537.36")

    try:
        # service = Service(ChromeDriverManager().install())
        # driver = webdriver.Chrome(service=service, options=chrome_options)
        options = webdriver.ChromeOptions()
        # 컨테이너 환경에서 안정적인 실행을 위한 필수 옵션들
        options.add_argument('--headless')           # 화면 없이 실행 (필수 권장)
        options.add_argument('--no-sandbox')         # 리눅스 환경 필수 옵션
        options.add_argument('--disable-dev-shm-usage') # 메모리 공유 문제 해결

        # [핵심 변경 포인트]
        # 'chrome'은 docker-compose.yml 파일에 적은 서비스 이름입니다.
        # 포트 4444는 Selenium Standalone Chrome의 기본 포트입니다.
        driver = webdriver.Remote(
            command_executor='http://chrome:4444/wd/hub',
            options=options
        )
    except Exception as e:
        print(f"WebDriver Manager 실패, 시스템 경로 사용 시도: {e}")
        # Colab 기본 경로 사용
        chrome_options.add_argument("--remote-debugging-port=9222")
        driver = webdriver.Chrome(options=chrome_options)

    driver.set_page_load_timeout(20)
    return driver

# ===================== 텍스트/숫자 파싱 (v4) =====================
def is_froala_footer(text: str) -> bool:
    if not text: return False
    return bool(re.search(r"Powered\s*by\s*Froala\s*Editor", text, flags=re.I | re.S))

def clean_line(text: str) -> str:
    if not text: return ""
    text = re.sub(r"Powered\s*by\s*Froala\s*Editor.*$", "", text, flags=re.I | re.S)
    text = text.replace("\xa0", " ")
    text = re.sub(r"\s+", " ", text).strip()
    text = re.sub(r"^\s*[-•]\s*", "- ", text)
    return text

def is_bullet_like_strong(s: str) -> bool:
    if not s: return False
    st = s.strip()
    if re.match(r"^[-•*]\s*", st): return True
    if len(st) >= 40: return True
    if re.search(r"(다\.|요\.|!|\?|:)$", st): return True
    return False

def parse_amount(text: str) -> int:
    if not text: return 0
    text = text.replace(",", "").replace(" ", "")
    match = re.search(r"(\d+)(천|만)?원?", text)
    if not match: return 0
    num = int(match.group(1))
    unit = match.group(2)
    if unit == "천": num *= 1000
    elif unit == "만": num *= 10000
    return num

# ===================== 테이블 파싱 (v4) =====================
def parse_table(table_tag):
    rows = []
    for tr in table_tag.find_all("tr"):
        cells = []
        for td in tr.find_all(["td", "th"]):
            text = clean_line(td.get_text(" ", strip=True))
            if text:
                cells.append(text)
        if any(cells):
            rows.append(cells)
    return rows

"""# [Cell 5] 카드 상세 정보 파싱 함수
5단계: 상세 파싱 함수 (필터링 로직 포함)
핵심 부분입니다. HTML 태그를 확인하여 단종 카드와 체크카드를 식별하고, 유효한 경우에만 데이터를 추출합니다.
"""

# ===================== 상세 파싱 (에러 수정 버전) =====================
def parse_card_detail(html: str, card_id: str, card_type: int) -> Optional[Dict[str, Any]]:
    soup = BeautifulSoup(html, "lxml")

    # 1. [안전 장치] 카드 이름 태그 찾기
    name_tag = soup.select_one("div.data_area > div.tit > strong.card")
    # print(f"카드 이름 태그 존재 : {card_id}")

    # ⚠️ 수정된 부분: 이름 태그가 없으면(잘못된 페이지면) 바로 포기하고 None 반환
    if not name_tag:
        # print(f"🔍 ID {card_id}: 카드 이름을 찾을 수 없음 (유효하지 않은 페이지)")
        return None

    # 2. 이름 추출 및 체크카드 필터링
    raw_name = name_tag.get_text(strip=True)

    # [필터링] 이름에 '체크' 또는 'check'가 있으면 제외
    if "체크" in raw_name or "check" in raw_name.lower():
        # print(f"⛔ [Filter] ID {card_id} 제외: 체크카드임 ({raw_name})")
        return None

    # 3. 데이터 구조 초기화
    card_data = {
        "card_id": card_id,
        "card_rank": None,
        "card_link": f"{DETAIL_BASE_URL}{card_id}",
        "card_name": raw_name,  # 추출한 이름 저장
        "card_company": "정보 없음",
        "card_type": card_type,
        "domestic_year_cost": 0,
        "abroad_year_cost": 0,
        "previous_month_performance": 0,
        "benefits": [],
    }

    # 4. 회사명
    company_tag = soup.select_one("div.data_area > div.tit > p.brand")
    if company_tag:
        card_data["card_company"] = company_tag.get_text(strip=True)

    # 5. 연회비 / 전월실적 파싱
    bnf2 = soup.select_one("div.bnf2")
    if bnf2:
        for dl in bnf2.select("dl"):
            dt, dd = dl.find("dt"), dl.find("dd")
            if not dt or not dd: continue

            key, val = dt.get_text(strip=True), dd.get_text(strip=True)
            if "연회비" in key:
                domestic = abroad = 0
                for span in dd.select("span"):
                    txt = span.get_text(strip=True)
                    if "국내" in txt:
                        domestic = parse_amount(txt)
                    elif "해외" in txt:
                        abroad = parse_amount(txt)

                if domestic == 0 and abroad > 0: domestic = abroad
                if abroad == 0 and domestic > 0: abroad = domestic

                card_data["domestic_year_cost"] = domestic
                card_data["abroad_year_cost"] = abroad
            elif "전월실적" in key:
                card_data["previous_month_performance"] = parse_amount(val)

    # 6. 혜택 파싱
    for dl in soup.select("div.lst.bene_area > dl"):
        title_tag = dl.select_one("dt > p.txt1")
        summary_tag = dl.select_one("dt > i")
        content_tag = dl.select_one("dd > div.in_box")

        if not title_tag or not content_tag:
            continue

        category = title_tag.get_text(strip=True)
        summary = summary_tag.get_text(strip=True) if summary_tag else None
        benefit_obj = {"category": category, "summary": summary, "subtitles": []}

        current_subtitle = None
        current_desc = []

        def flush_sub():
            if current_subtitle or current_desc:
                benefit_obj["subtitles"].append({
                    "subtitle": current_subtitle or summary or category,
                    "descriptions": current_desc.copy()
                })
                current_desc.clear()

        for child in content_tag.children:
            if getattr(child, "name", None) == "p":
                text = child.get_text(" ", strip=True)
                if not text: continue

                # is_froala_footer 함수가 정의되어 있어야 함 (없으면 생략 가능)
                try:
                    if is_froala_footer(text): continue
                except: pass

                strong_el = child.find("strong")
                if strong_el:
                    strong_text = strong_el.get_text(strip=True)
                    flush_sub()
                    current_subtitle = strong_text
                    continue

                # clean_line 함수가 정의되어 있어야 함
                try:
                    current_desc.append(clean_line(text))
                except:
                    current_desc.append(text)

            elif getattr(child, "name", None) == "table":
                # 테이블 파싱 로직 (필요시 추가)
                pass

        flush_sub()
        card_data["benefits"].append(benefit_obj)

    return card_data

# ===================== 상세 페이지 스크래핑 (v4 로직) =====================
def scrape_card_detail(driver, card_id: str, card_type: int):
    """Selenium으로 상세 페이지를 스크래핑하고 파싱 함수를 호출합니다."""
    url = f"{DETAIL_BASE_URL}{card_id}"
    try:
        driver.get(url)
        # 쿠키 팝업 처리
        try:
            cookie_button = WebDriverWait(driver, 3).until(
                EC.element_to_be_clickable((By.CSS_SELECTOR, "div.pop_cookie_wrap button.btn_agree"))
            )
            cookie_button.click()
            time.sleep(0.5)
        except TimeoutException:
            pass # 쿠키 팝업이 없으면 통과

        # 혜택 상세 내용이 로드되도록 스크롤 및 클릭 (v4 로직)
        driver.execute_script("window.scrollTo(0, document.body.scrollHeight);")
        time.sleep(0.5) # 스크롤 대기

        dl_elements = driver.find_elements(By.CSS_SELECTOR, "div.lst.bene_area > dl")
        for dl in dl_elements:
            dt = dl.find_element(By.CSS_SELECTOR, "dt")
            if "on" not in dl.get_attribute("class"):
                try:
                    # element가 클릭 가능하도록 스크롤
                    driver.execute_script("arguments[0].scrollIntoView(true);", dt)
                    time.sleep(0.1)
                    driver.execute_script("arguments[0].click();", dt)
                    time.sleep(0.2) # 아코디언 열리는 시간
                except Exception:
                    pass # 클릭 실패해도 일단 진행

        # 파싱할 영역이 로드되었는지 최종 확인
        WebDriverWait(driver, 8).until(EC.presence_of_element_located((By.CSS_SELECTOR, "div.lst.bene_area")))

        # HTML을 파싱 함수로 전달
        return parse_card_detail(driver.page_source, card_id, card_type)

    except Exception as e:
        print(f"❌ 카드 ID {card_id} (Type: {card_type}) Selenium 스크래핑 실패: {e}")
        return None

"""# [Cell 3] 기본 설정 및 경로 지정"""

import os
import json
import time
import random
import re
from tqdm import tqdm
from bs4 import BeautifulSoup
from selenium import webdriver
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.chrome.service import Service

# ===================== 설정 영역 =====================
# 수집할 카드 ID 범위 (요청하신 2401 ~ 2800)
# START_ID = 2665
# END_ID   = 2670

# api(필터링용)
API_BASE_URL = "https://www.card-gorilla.com/card/detail/{id}"

# 기본 URL
DETAIL_BASE_URL = "https://www.card-gorilla.com/card/detail/"


# API 요청 설정
TOTAL_START_ID = 1
TOTAL_END_ID   = 2
BATCH_SIZE     = 400
RETRY_BACKOFF_FACTOR = 0.8

# 저장 경로 설정
drive_root = "/opt/airflow/dags/my_utils/data/crawling_data"

from datetime import datetime

# 오늘 날짜 가져오기
today = datetime.now()

# YYYYMMDD 형식으로 포맷팅
formatted_date = today.strftime("%Y%m%d")

target_folder_name = formatted_date

# 폴더 생성
target_folder_path = os.path.join(drive_root, target_folder_name)
if not os.path.exists(target_folder_path):
    os.makedirs(target_folder_path)
    print(f"📂 폴더 생성: {target_folder_path}")
else:
    print(f"📂 폴더 확인: {target_folder_path}")

# 최종 저장 파일명 (신용카드만 저장)
# CREDIT_CARD_FILE_NAME = f"cardgorilla_credit_cards_v2_{target_folder_name}_{START_ID}_{END_ID}.json"
# OUTPUT_FILE = os.path.join(target_folder_path, CREDIT_CARD_FILE_NAME)

# print(f"💾 최종 저장 경로: {OUTPUT_FILE}")

"""# 최종 코드"""
# [Cell 6] 메인 실행 코드 (멀티 프로세싱 적용)

import os
import json
import time
import random
from tqdm import tqdm
from concurrent.futures import ThreadPoolExecutor # I/O 바운드 작업에 적합

# ===================== 설정 영역 =====================
# 수집할 카드 ID 범위 (작동 확인을 위해 1~5로 설정)

# 동시에 실행할 Selenium 브라우저 개수 (PC 성능에 따라 3~10 사이로 조절)
MAX_WORKERS    = 5 

# 기존 설정값 재사용
# drive_root, target_folder_name, target_folder_path, API_BASE_URL, DETAIL_BASE_URL 등은
# 앞선 Cell 3에서 정의된 변수를 사용합니다.

# ===================== 병렬 처리를 위한 래퍼 함수 =====================
def process_single_card(card_id_num: int, target_folder_path: str):
    """
    단일 카드 ID를 처리하는 함수.
    이 함수는 각 스레드(또는 프로세스)에서 개별적으로 실행됩니다.
    """
    card_id_str = str(card_id_num)
    driver = None
    session = None
    
    try:
        # 1. API 세션 설정 (각 스레드/프로세스마다 설정)
        session = build_session()
        
        # 2. API로 카드 정보 호출 및 1차 필터링
        api_data = fetch_card(session, card_id_num)
        api_success = True

        if api_data is None or any(k in api_data for k in ("_error", "_http_status", "_parse_error")):
            api_success = False
            api_data = {}
        
        if api_success:
            if is_discontinued(api_data):
                return None # 단종 카드
            api_type_str = str(api_data.get('cardType') or api_data.get('type') or '').upper()
            if "CHECK" in api_type_str or "체크" in api_type_str:
                return None # 체크 카드

        # 3. Selenium 드라이버 시작 (각 스레드/프로세스마다 개별 브라우저 실행)
        driver = setup_driver()
        
        # 4. Selenium 상세 스크래핑 (기존 scrape_card_detail 함수 사용)
        card_type_guess = 0 # 신용카드
        data = scrape_card_detail(driver, card_id_str, card_type_guess)

        if data == "DISCONTINUED" or data == "CHECK_CARD" or data is None:
            return None
        
        if isinstance(data, dict) and data.get("card_name") != "정보 없음":
            # 최종 저장 전 이름으로 한 번 더 체크카드 검사
            if "체크" in data['card_name'] or "check" in data['card_name'].lower():
                return None
            else:
                return data # 유효한 신용카드 데이터 반환

    except Exception as e:
        # 에러 발생 시 로그 출력 후 None 반환
        print(f"❌ ID {card_id_str} 처리 중 오류: {e}")
        return None
        
    finally:
        # 5. 드라이버와 세션 정리 (필수)
        if driver:
            try:
                driver.quit()
            except:
                pass
        if session:
            try:
                session.close()
            except:
                pass
        # 서버 부하 조절 (동시 실행이므로 대기 시간은 짧게)
        time.sleep(random.uniform(0.1, 0.3))

    return None # 최종적으로 데이터가 없는 경우

# ===================== 메인 실행 코드 =====================
def crawling_main():
    total_start_time = time.time()
    all_results = []
    
    # 400개씩 끊어서 배치 처리 (기존 로직 유지)
    for batch_start in range(TOTAL_START_ID, TOTAL_END_ID + 1, BATCH_SIZE):
        batch_end = min(batch_start + BATCH_SIZE - 1, TOTAL_END_ID)

        print(f"\n========================================================")
        print(f"🔄 [Batch Start] ID 범위: {batch_start} ~ {batch_end} (동시 실행 수: {MAX_WORKERS})")
        print(f"========================================================")

        card_ids_to_process = list(range(batch_start, batch_end + 1))
        current_batch_results = []

        # ThreadPoolExecutor를 사용하여 병렬 실행
        with ThreadPoolExecutor(max_workers=MAX_WORKERS) as executor:
            # map 함수를 사용하여 process_single_card 함수에 ID 리스트를 전달하고 실행
            # (tqdm을 적용하여 진행 상황을 표시)
            tasks = [executor.submit(process_single_card, cid, target_folder_path) for cid in card_ids_to_process]
            
            for future in tqdm(tasks, total=len(tasks), desc=f"Batch {batch_start}~{batch_end}"):
                result = future.result()
                if result:
                    current_batch_results.append(result)
        
        # ---------------------------------------------------------
        # 배치 종료 및 파일 저장
        # ---------------------------------------------------------
        if current_batch_results:
            all_results.extend(current_batch_results)
            # 파일명 예: cardgorilla_credit_cards_v2_1_400.json
            filename = f"cardgorilla_credit_cards_v2_airflow_{batch_start}_{batch_end}.json"
            filepath = os.path.join(target_folder_path, filename)

            with open(filepath, "w", encoding="utf-8") as f:
                json.dump(current_batch_results, f, ensure_ascii=False, indent=2)

            print(f"💾 저장 완료: {filepath} (총 {len(current_batch_results)}개)")
        else:
            print(f"⚠️ 저장할 데이터 없음 (Batch {batch_start}~{batch_end})")
        
        time.sleep(2)

    print("\n🎉 모든 배치 작업이 완료되었습니다!")
    total_time = time.time() - total_start_time
    print(f"\n🎉 전체 작업 완료! 소요 시간: {total_time:.2f}초")
    print(f"✨ 최종 수집된 유효 신용카드 총 개수: {len(all_results)}개")

if __name__ == "__main__":
    crawling_main()